name: Publish Library in NPM
on:
  release:
    types:
      - created
jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Package
        run: yarn pack
  build:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: write # for uploading attestations.
      actions: read
    needs: prepare
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@d377044abc3274a420a70e95ca65a22c95c04dbe
    with:
      node-version: 18.16.0
  publish:
    id: publish
    uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@7f4fdb871876c23e455853d694197440c5a91506 # v1.5.0
    with:
      access: public
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
      package-name: ${{ needs.build.outputs.package-name }}
      package-download-name: ${{ needs.build.outputs.package-download-name }}
      package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
      provenance-name: ${{ needs.build.outputs.provenance-name }}
      provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
      provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}

