name: Publish Library in NPM
on:
  release:
    types:
      - created
jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Package
        run: yarn pack
  publish:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: write # for uploading attestations.
      actions: read
    needs: prepare
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@5dfe44f2f2806e28957c9de7aaa1fb9973921187
    with:
      node-version: 18.16.0
    secrets:
      node-auth-token: ${{ secrets.NPM_TOKEN }}
