name: Publish Library in NPM
on:
  release:
    types:
      - created
jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Package
        run: yarn pack
  build:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: write # for uploading attestations.
      actions: read
    needs: prepare
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@0779f7bec68e2bf54a7b0a32bf4763f25ab29702 # v1.6.0
    with:
      node-version: 18.16.0
  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@0779f7bec68e2bf54a7b0a32bf4763f25ab29702 # v1.6.0
        with:
          access: public
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ${{ needs.build.outputs.package-name }}
          package-download-name: ${{ needs.build.outputs.package-download-name }}
          package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
          provenance-name: ${{ needs.build.outputs.provenance-name }}
          provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
          provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}
